### PR TITLE
Fix interactive render crash on cancel

### LINKED ISSUE #341: Interactive rendering crashes Max when closing framebuffer window
Looks like a regression. I'll make a PR with fixes shortly.

### PR DESCRIPTION
**Pull request by usakhelo**
This should fix #341 
Reference to destructed local variable `search_paths` was kept in `MasterRenderer` class.

### CODE REVIEW

File: src/appleseed-max-impl/appleseedinteractive/interactivesession.h [hunk 1]
```diff
@@ -43,8 +43,10 @@
 #include <thread>
 
 // Forward declarations.
-namespace renderer { class Camera; }
-namespace renderer { class Project; }
+namespace foundation { class SearchPaths; }
```
Comment (dictoon) [inline src/appleseed-max-impl/appleseedinteractive/interactivesession.h]: A forward declaration is actually not enough in this case, you'll need to include `foundation/utility/searchpaths.h`.

Comment (usakhelo) [reply src/appleseed-max-impl/appleseedinteractive/interactivesession.h]: I thought the same but it compiled and thought I still don't understand anything about c++ :)

Comment (dictoon) [reply src/appleseed-max-impl/appleseedinteractive/interactivesession.h]: What most likely happens is that `SearchPaths` is already made available by an indirect `#include` statement, and the forward declaration is entirely redundant.
