### PR TITLE
Fix titles on small texture buttons

### LINKED ISSUE #11: Map buttons should display an M when maps are assigned

### PR DESCRIPTION
**Pull request by usakhelo**
Hi, 
this is small interface change, should fix #11

image

I thought it's good time to fix it before other materials are added.
Thanks,
Sergo.

### CODE REVIEW

File: src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.h [hunk 1]
```diff
@@ -174,6 +174,16 @@ class AppleseedDisneyMtl
...
+//
+// Texture parameter accessor class declaration
+//
+
+class TexturePBAccessor
+    : public PBAccessor
+{
+public:
+    void Set(PB2Value& v, ReferenceMaker* owner, ParamID id, int tabIndex, TimeValue t) override;
+};
```
Comment (usakhelo) [inline src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.h]: I could probably put this class into utilities for other materials to access it.

File: src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.h [hunk 2]
```diff
@@ -174,6 +174,16 @@ class AppleseedDisneyMtl
         const char*         name);
 };
 
+//
+// Texture parameter accessor class declaration
+//
+
+class TexturePBAccessor
+    : public PBAccessor
```
Comment (dictoon) [inline src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.h]: Half indentation here.

File: src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.h [hunk 3]
```diff
@@ -174,6 +174,16 @@ class AppleseedDisneyMtl
...
+{
+public:
```
Comment (dictoon) [inline src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.h]: Here too.

File: src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.h [hunk 4]
```diff
@@ -174,6 +174,16 @@ class AppleseedDisneyMtl
         const char*         name);
 };
 
+//
+// Texture parameter accessor class declaration
```
Comment (dictoon) [inline src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.h]: End full line comment with a period.

Comment (dictoon) [reply src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.h]: I think you can also remove the "class declaration" part.

File: src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.h (hunk 1 above)
Comment (dictoon) [reply src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.h]: Yes, absolutely! You can add it to `utilities.{h,cpp}` in the "Parameter blocks functions" section. However it looks like the implementation of this class is specific to the Disney material right now.

File: src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.cpp [hunk 5]
```diff
@@ -919,6 +958,35 @@ asf::auto_release_ptr<asr::Material> AppleseedDisneyMtl::create_builtin_material
...
+//
+
+void TexturePBAccessor::Set(
+    PB2Value&         v,
+    ReferenceMaker*   owner,
+    ParamID           id,
+    int               tabIndex,
+    TimeValue         t)
+{
+    if (id == ParamIdBaseColorTexmap)
```
Comment (dictoon) [inline src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.cpp]: Why is there an exception for `ParamIdBaseColorTexmap`?

File: src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.cpp [hunk 6]
```diff
@@ -168,6 +169,33 @@ namespace
...
+    {
+        if (pblock == nullptr)
+            return;
+
+        IParamMap2* map = pblock->GetMap(ParamMapIdDisney);
+        if (map == nullptr)
+            return;
+
+        const int count = pblock->NumParams();
+        for (int i=0; i < count; ++i)
```
Comment (dictoon) [inline src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.cpp]: Add spaces around `=`.

File: src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.cpp [hunk 7]
```diff
@@ -168,6 +169,33 @@ namespace
...
+        {
+            const int param_id = pblock->IndextoID(i);
+            if (param_id == ParamIdBaseColorTexmap)
```
Comment (dictoon) [inline src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.cpp]: Again, not sure why this exception?

File: src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.cpp [hunk 8]
```diff
@@ -168,6 +169,33 @@ namespace
         ParamIdBumpTexmap
     };
 
+    void update_map_buttons(IParamBlock2* pblock)
```
Comment (dictoon) [inline src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.cpp]: Do we really need this function _and_ the `TexturePBAccessor` class?

Comment (usakhelo) [reply src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.cpp]: Agree it's crazy. I think I can get rid of accessor and put the same code into setsubtexmap function.

File: src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.cpp (hunk 7 above)
Comment (usakhelo) [reply src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.cpp]: It's because base color texture button is wide and contains full name. But I'll get rid of this check I think.

File: src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.h (hunk 1 above)
Comment (usakhelo) [reply src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.h]: I'll put update_buttons function into utilities.

File: src/appleseed-max-impl/utilities.cpp [hunk 9]
```diff
@@ -128,6 +129,29 @@ WStr replace_extension(const WStr& file_path, const WStr& new_ext)
...
 
+void update_map_buttons(IParamMap2* param_map)
+{
+    if (param_map == nullptr)
+        return;
+
+    IParamBlock2* param_block = param_map->GetParamBlock();
+
+    const int count = param_block->NumParams();
+    for (int i = 0; i < count; ++i)
```
Comment (dictoon) [inline src/appleseed-max-impl/utilities.cpp]: An elegant idiom we use all the time is this:

    for (int i = 0, e = param_block->NumParams(); i < e; ++i)

(`e` for "end")

You don't have to use it, but it's good to know it.

File: src/appleseed-max-impl/utilities.cpp [hunk 10]
```diff
@@ -128,6 +129,29 @@ WStr replace_extension(const WStr& file_path, const WStr& new_ext)
...
+    {
+        const int param_id = param_block->IndextoID(i);
+        const ParamDef& param_def = param_block->GetParamDef(param_id);
+        if (param_def.type == TYPE_TEXMAP && (param_def.flags & P_NO_AUTO_LABELS))
+        {
+            const auto texmap = param_block->GetTexmap(param_id, GetCOREInterface()->GetTime(), FOREVER);
+            if (texmap == nullptr)
```
Comment (dictoon) [inline src/appleseed-max-impl/utilities.cpp]: That looks perfectly fine. Here's a compact alternative:

    param_map->SetText(param_id, texmap == nullptr ? L"" : L"M");

File: src/appleseed-max-impl/utilities.h [hunk 11]
```diff
@@ -134,6 +134,7 @@ BOOL get_paramblock_value_by_name(
     Interval&               validity,
     const int               tab_index = 0);
 
+void update_map_buttons(IParamMap2* param_map);
```
Comment (dictoon) [inline src/appleseed-max-impl/utilities.h]: Add blank line after this since block comments must be preceded by two blank lines.

File: src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.cpp [hunk 12]
```diff
@@ -591,6 +600,8 @@ Interval AppleseedDisneyMtl::Validity(TimeValue t)
 ParamDlg* AppleseedDisneyMtl::CreateParamDlg(HWND hwMtlEdit, IMtlParams* imp)
 {
     ParamDlg* param_dialog = g_appleseed_disneymtl_classdesc.CreateParamDlgs(hwMtlEdit, imp, this);
+    if (m_pblock != nullptr)
```
Comment (dictoon) [inline src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.cpp]: Can `m_pblock` be null?

File: src/appleseed-max-impl/utilities.cpp (hunk 9 above)
Comment (usakhelo) [reply src/appleseed-max-impl/utilities.cpp]: Yes! Now I remember you told me that before. But I couldn't remember by myself. Thanks!

File: src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.cpp (hunk 12 above)
Comment (usakhelo) [reply src/appleseed-max-impl/appleseeddisneymtl/appleseeddisneymtl.cpp]: I don't know honestly. I can put assert and try to do something with materials and see if it crashes.

**Comment by usakhelo** [comment]
I've changed m_pblock check to dbgassert and it worked fine. I'm still not sure if it can be null there, but let's see.
I'll merge this and fix other materials, looks like Glass and SSS have small texture buttons.
