### PR TITLE
Fix environment background rotation issues

### LINKED ISSUE #258: V offset is reversed
At least when rotating environment maps, the effect it has on the render is the opposite of the effect it has on the material preview.

### PR DESCRIPTION
**Pull request by Mango-3**
-Aligns the environment map(HDR) orientation with the Max viewport preview
-Allows environment map rotation via the Max Bitmap U,V Offset and U,V Angle controls
-Allows horizontal/vertical flipping via setting the U,V Tiling value ±1.  
-Fixes #258 and #55 

Screenshot shows test render and background preview coinciding (U & V Offset applied).
env_fix

### CODE REVIEW

File: src/appleseed-max-impl/appleseedrenderer/projectbuilder.cpp [hunk 1]
```diff
@@ -1368,19 +1368,33 @@ namespace
                 }
             }
 
+            asf::Vector3d UVFlip_vec(-1,1,1);
```
Comment (dictoon) [inline src/appleseed-max-impl/appleseedrenderer/projectbuilder.cpp]: We use snake_case for variable names: `uv_flip_vec`.

Add spaces after commas.

Spell out floating constants: 1.0.

File: src/appleseed-max-impl/appleseedrenderer/projectbuilder.cpp [hunk 2]
```diff
@@ -1368,19 +1368,33 @@ namespace
...
             UVGen* uvgen = rend_params.envMap->GetTheUVGen();
             if (uvgen && uvgen->IsStdUVGen())
             {
                 StdUVGen* std_uvgen = static_cast<StdUVGen*>(uvgen);
-                env_edf_params.insert("horizontal_shift", std_uvgen->GetUOffs(time) * 180.0f + 90.0f);
-                env_edf_params.insert("vertical_shift", std_uvgen->GetVOffs(time) * 180.0f);
+
+                float h_shift = std_uvgen->GetUOffs(time) * 360.0f + 90.0f + asf::rad_to_deg(std_uvgen->GetUAng(time));
```
Comment (dictoon) [inline src/appleseed-max-impl/appleseedrenderer/projectbuilder.cpp]: Make const.
